name: Deploy to EC2 via ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  IMAGE_TAG: latest
  ECR_ACCOUNT_ID: 905418480679
  ECR_REPOSITORY: jsg-ml
  ECR_REGISTRY: 905418480679.dkr.ecr.ap-northeast-2.amazonaws.com
  IMAGE_URI: 905418480679.dkr.ecr.ap-northeast-2.amazonaws.com/jsg-ml:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 905418480679.dkr.ecr.ap-northeast-2.amazonaws.com
            docker pull 905418480679.dkr.ecr.ap-northeast-2.amazonaws.com/jsg-ml:latest
            docker rm -f jsg-ml-running || true
            
            cat <<EOF > /home/ubuntu/.env
            DATABASE_USER_NAME=${{ secrets.DB_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}
            DATABASE_ENDPOINT=${{ secrets.DB_ENDPOINT }}
            DATABASE_NAME=${{ secrets.DB_NAME }}
            DATABASE_PORT=${{ secrets.DB_PORT }}
            EOF

            docker run -d -p 8000:8000 \
              --env-file /home/ubuntu/.env \
              --name jsg-ml-running \
              905418480679.dkr.ecr.ap-northeast-2.amazonaws.com/jsg-ml:latest